site_name: Mad-Pascal
site_author: TeBe
site_description: "Mad-Pascal Documentation"
site_keyword: "cross-compiler"

repo_url: https://github.com/tebe6502/Mad-Pascal

theme:
    name: readthedocs
    hljs_languages:
        - delphi

nav:
    - Introduction: introduction.md
    - Memory map: map.md
    - Usage: usage.md
    - Syntax: syntax.md
    - Constants: constants.md
    - Types: types.md
    - Instructions: instructions.md
    - Macros: macros.md
    - Assembly instructions: asm.md
    - Resource files: resources.md
    - Procedures, functions, modifiers: procedures-functions.md
    - Interrupt handling: interrupts.md
    - Units: units.md
    - Essential Libraries: essential-libraries.md
    - Examples: examples.md
    - Projects: projects.md
